import './globals.css'
import { Inter } from 'next/font/google'
import NavMenu from './navMenu'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Play-on Lightup Objective',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavMenu></NavMenu>
        {children}
        </body>
    </html>
  )
}
